In [1]:
import torch

In [4]:
print(torch.__version__)

2.5.1+cu124


In [5]:
if torch.cuda. is_available():
  print("GPU IS AVAILABLE")
else:
  print("USE CPU")
  _

USE CPU


#Creating Tensor

In [12]:
torch.empty(2,3)

tensor([[1.6940e-33, 0.0000e+00, 2.1832e-33],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
type(a)

torch.Tensor

In [10]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [13]:
torch.rand(2,3)

tensor([[0.8886, 0.2576, 0.9104],
        [0.4648, 0.7473, 0.3376]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [17]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [20]:
torch.linspace(0,10,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [21]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# **Tensor Shapes**

In [23]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[    132455929015696,           155457264,                   0],
        [                  0,                   0, 7310593858020254331]])

# **Tensor Data Type**

In [27]:
x.dtype

torch.int64

In [29]:
torch.tensor([1,2,3],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
a=torch.tensor([1,2,3])

In [32]:
a.dtype

torch.int64

In [33]:
a.to(torch.float32)

tensor([1., 2., 3.])

In [34]:
torch.randint(size=(2,3),low=0,high=10)

tensor([[2, 8, 8],
        [0, 4, 3]])